# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kpesonen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/03/06 12:32:44 by kpesonen          #+#    #+#              #
#    Updated: 2020/03/06 12:32:51 by kpesonen         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#From a debian image you will add the appropriate sources to create a TeamSpeak
#server, that will launch along with your container. It will be deemed valid if at least
#one user can connect to it and engage in a normal discussion (no far-fetched setup), so
#be sure to create your Dockerfile with the right options. Your program should get the
#sources when it builds, they cannot be in your repository
